Repository wecode-bootcamp-korea/25-1st-MECOOK-frontend, pull requests merged in 2021-10, with the labels that each got.

#15 [25기 김용현] Footer 별도 branch로 분리
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#5 [25기 서고운] login 페이지 레이아웃 및 기능 구현
  src/pages/Login/Close.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/styles/common.scss
  src/styles/reset.scss
  src/styles/variable.scss
Labels: Status: 리뷰 요청

#4 [25기 손호영] 상세 페이지 기본 레이아웃 및 애니매이션 구현
  public/data/data.json
  src/Routes.js
  src/index.js
  src/pages/ProductDetail/DetailImageBottom/DetailImageBottom.js
  src/pages/ProductDetail/DetailImageBottom/DetailImageBottom.scss
  src/pages/ProductDetail/DetailImageLeft/DetailImageLeft.js
  src/pages/ProductDetail/DetailImageLeft/DetailImageLeft.scss
  src/pages/ProductDetail/DetailImageRight/DetailImageRight.js
  src/pages/ProductDetail/DetailImageRight/DetailImageRight.scss
  src/pages/ProductDetail/DetailImageTop/DetailImageTop.js
  src/pages/ProductDetail/DetailImageTop/DetailImageTop.scss
  src/pages/ProductDetail/NutritionTable(영양성분)/NutritionTable.js
  src/pages/ProductDetail/NutritionTable(영양성분)/NutritionTable.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/ProductExplan/ProductExplan.js
  src/pages/ProductDetail/ProductExplan/ProductExplan.scss
  src/pages/ProductDetail/ProductInfo/Btn/AddCartBtn/AddCartBtn.js
  src/pages/ProductDetail/ProductInfo/Btn/AddCartBtn/AddCartBtn.scss
  src/pages/ProductDetail/ProductInfo/Btn/Btn.js
  src/pages/ProductDetail/ProductInfo/Btn/Btn.scss
  src/pages/ProductDetail/ProductInfo/Btn/LikeBtn/LikeBtn.js
  src/pages/ProductDetail/ProductInfo/Btn/LikeBtn/LikeBtn.scss
  src/pages/ProductDetail/ProductInfo/Btn/ProductCountBtn/ProductCountBtn.js
  src/pages/ProductDetail/ProductInfo/Btn/ProductCountBtn/ProductCountBtn.scss
  src/pages/ProductDetail/ProductInfo/ProductInfo.js
  src/pages/ProductDetail/ProductInfo/ProductInfo.scss
  src/pages/ProductDetail/TagBottom/TagBottom.js
  src/pages/ProductDetail/TagBottom/TagBottom.scss
  src/styles/common.scss
  src/styles/variable.scss
Labels: Status: 추가 기능 구현중, Status: 리뷰 요청

#18 [25기 김용현] best메뉴 탭 레이아웃 완성
  src/Routes.js
  src/pages/BestProduct/BestProduct.js
  src/pages/BestProduct/BestProduct.scss
  src/pages/ProductList/ProductPreview/ProductPreview.scss
Labels: Status: 리뷰 요청

#17 [25기 김용현] 검색 결과창 초기 레이아웃
  src/pages/SearchResult/SearchResult.js
  src/pages/SearchResult/SearchResult.scss
Labels: Status: 추가 기능 구현중
